### ISSUE TITLE
Private Key Issue

### ISSUE THREAD

**Issue by rhuab** [gauss-project/aurorafs#235]
How to get private key from a ubuntu node?

This is my data directory structure:

> xxx@iZj6ceuntkc5q6o40yyqitZ:~/aurora$ ls aurorafs/

> keys  localstore  statestore

> xxx@iZj6ceuntkc5q6o40yyqitZ:~/aurora$ ls aurorafs/keys/

> boson.key  libp2p.key

> xxx@iZj6ceuntkc5q6o40yyqitZ:~/aurora$ ls aurorafs/localstore/

> 000014.ldb  000015.ldb  000018.ldb  000019.log  CURRENT  CURRENT.bak  LOCK  LOG  MANIFEST-000020

**Comment by deanaufs** [comment]
u can use dashboard  [www.aufs.io/dashboard](url)
